import Head from 'next/head'
import Image from 'next/image'
import { Fascinate_Inline, Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
// import image from "../public/images/cherrydeck-rMILC1PIwM0-unsplash (1).jpg"
import classes from "./home.module.css"
import Link from 'next/link'
import { Fragment, useState } from 'react'
import Landing from '@/components/homepage/landing'
import Education from '@/components/homepage/Education'

export default function Home() {



// I can't tell you how many times I changed the css and complete layout



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <Landing /> 
      <Education />
      <Fragment>
        <h2 className='transitionCenter whiteText'>About Impresario</h2>

        <div className={`${classes.leftRight} whiteText`}>
           <div className={`${classes.title}`}><h3>The Entrepreneur of Impresario</h3></div>
           <div className={`${classes.left}`}></div>
           <div className={`${classes.right}`} ><p>Hi, I'm Jake, I've held many titles. Raft Guide, Musician, Biologist, Software Engineer,  and now Entrepreneur. </p>
          <p>In any role I've held I've put nothing but my whole heart into it.
            I want to help others that are passionate about their craft get their products out in the world.
          </p>
          <p>So I built Impresario, A way for your ideas to vibrate at the tone of Googles Search Engine Optimization</p>
          <p>Impresario gives the power for you to build your own site, or have it built for you. </p>
          <p>Let's take back business from large corporations and bring it back to you!</p>
          </div>
        </div>
        <div className={`${classes.leftRight} whiteText`}>
           <div className={`${classes.title}`}><h3>The Mission of impresario</h3></div>
           <div className={`${classes.lowerRight}`}></div>
           <div className={`${classes.lowerLeft}`} ><p>To facilitate the self actualization of those surrounding impresario. </p>
          <p>By elegantly conveying your passions to the web.
          </p>
          <p>And empowering you with education.</p>
          <p>We want you to be successful in business and happiness, and to proceed forward courageously. </p>
          <p>And become the cultivation of community that impresario is.</p>
          </div>
        </div>
      </Fragment>

      </main>
    </>
  )
}



